![imagen](./img/ejercicios.png)

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [1]:
# "import numpy as np" significa:
# "carga la librería numpy y de ahora en adelante llámala np"
# Le ponemos el alias "np" para no tener que escribir "numpy" cada vez
import numpy as np

# __version__ es un atributo especial que tienen las librerías
# con el número de versión instalada
print(np.__version__)

2.4.2


## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [2]:
# np.arange(10) genera números del 0 al 9 (no llega al 10, igual que range)
my_array = np.arange(10)

print(my_array)
# resultado: [0 1 2 3 4 5 6 7 8 9]

[0 1 2 3 4 5 6 7 8 9]


## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [3]:
# Para crear arrays rellenos de un valor usamos np.ones() (unos) o np.zeros() (ceros). Para True/False le decimos qué tipo de dato queremos con dtype=bool.
# np.ones((3,3)) crea un array de 3 filas x 3 columnas lleno de 1s
# dtype=bool convierte esos 1s en True (en booleano, 1 = True)
array_true = np.ones((3, 3), dtype=bool)

print(array_true)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## Ejercicio 4
Extrae todos los impares de `my_array`

In [4]:
# my_array es [0 1 2 3 4 5 6 7 8 9]

# PASO 1: creamos la máscara
# % calcula el RESTO de dividir
# 1 % 2 = 1  (impar, resto 1)
# 2 % 2 = 0  (par, resto 0)
# != significa "distinto de"
mascara = my_array % 2 != 0

print(mascara)
# [False  True False  True False  True False  True False  True]
#    0      1     2     3     4     5     6     7     8     9

# PASO 2: aplicamos la máscara al array
# Donde hay True se queda, donde hay False desaparece
impares = my_array[mascara]
print(impares)
# [1 3 5 7 9]

# Se puede escribir en una sola línea:
impares = my_array[my_array % 2 != 0]
print(impares)
# [1 3 5 7 9]

[False  True False  True False  True False  True False  True]
[1 3 5 7 9]
[1 3 5 7 9]


## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [5]:
# .copy() crea una copia INDEPENDIENTE
# Si no usamos copy() y modificamos nuevo_array,
# también se modificaría my_array (comparten memoria)
nuevo_array = my_array.copy()

# Donde el elemento sea impar, lo sustituimos por -1
# Esto es: "en nuevo_array, en las posiciones donde haya impares, pon -1"
nuevo_array[nuevo_array % 2 != 0] = -1

print(nuevo_array)
# [ 0 -1  2 -1  4 -1  6 -1  8 -1]

print(my_array)
# [0 1 2 3 4 5 6 7 8 9]  # el original no ha cambiado

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [6]:
# ¿es impar? entonces pon -1
# ¿no es impar (es par)? entonces deja el valor original (my_array)
nuevo_array_where = np.where(my_array % 2 != 0, -1, my_array)

print(nuevo_array_where)
# [ 0 -1  2 -1  4 -1  6 -1  8 -1]

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [7]:
# reshape(filas, columnas)
# 2 filas x 5 columnas = 10 elementos 
array_2d = my_array.reshape(2, 5)

print(array_2d)
# [[0 1 2 3 4]
#  [5 6 7 8 9]]

[[0 1 2 3 4]
 [5 6 7 8 9]]


## Ejercicio 8
Concatena los siguientes arrays verticalmente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [8]:
# Primero creamos los dos arrays que nos dan
a = np.arange(10).reshape(2, -1)  # reshape(2, -1): 2 filas, las columnas que salgan automáticamente
b = np.repeat(1, 10).reshape(2, -1)  # np.repeat(1, 10) crea [1,1,1,1,1,1,1,1,1,1] y lo ponemos en 2x5

# np.vstack() apila los arrays uno DEBAJO del otro (v = vertical)
# a tiene 2 filas y b tiene 2 filas → el resultado tiene 4 filas
resultado = np.vstack((a, b))
print(resultado)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [9]:
# Usamos los mismos arrays del ejercicio anterior
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)

# np.hstack() apila los arrays uno AL LADO del otro (h = horizontal)
# a tiene 5 columnas y b tiene 5 columnas → el resultado tiene 10 columnas
resultado = np.hstack((a, b))
print(resultado)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa la función `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [10]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# np.intersect1d() nos da los elementos que están en AMBOS arrays
# Es como decir: "¿qué números aparecen tanto en a como en b?"
comunes = np.intersect1d(a, b)
print(comunes)
# [2 4] → el 2 y el 4 están en ambos arrays

[2 4]


## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

In [11]:
# help() nos muestra la documentación de cualquier función
# Nos dice qué hace, qué parámetros acepta y ejemplos de uso
help(np.concatenate)

Help on _ArrayFunctionDispatcher in module numpy:

concatenate(arrays, /, axis=0, out=None, *, dtype=None, casting='same_kind')
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.
    
        .. versionadded:: 1.20.0
    
    casting : {'no', 'equiv', 'safe', 'same_kind', 'unsafe'}, 

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento de `my_array`
3. Accede al último elemento de `my_array`
4. Imprime por pantalla los numeros del 1 al 7 de `my_array`

In [12]:
my_array = np.arange(10)

# 1. Multiplicamos cada elemento por 10
# Numpy multiplica TODOS los elementos a la vez (no necesitamos un for)
por_diez = my_array * 10
print("Multiplicado por 10:", por_diez)

# 2. Primer elemento: posición 0 (las listas empiezan en 0)
print("Primer elemento:", my_array[0])

# 3. Último elemento: posición -1 (el -1 significa "el último")
print("Último elemento:", my_array[-1])

# 4. Del 1 al 7: posiciones 1 a 7 (el 8 no se incluye)
print("Del 1 al 7:", my_array[1:8])

Multiplicado por 10: [ 0 10 20 30 40 50 60 70 80 90]
Primer elemento: 0
Último elemento: 9
Del 1 al 7: [1 2 3 4 5 6 7]


## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [13]:
# np.array() con una lista de listas crea una matriz
# Cada lista interior es una fila
my_matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(my_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [14]:
# np.arange(inicio, fin, paso)
# Empieza en 1, termina antes de 50, y va de 3 en 3
secuencia = np.arange(1, 50, 3)
print(secuencia)

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]


## Ejercicio 15
Obtén la siguiente secuencia

```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

In [15]:
# np.arange() también funciona con decimales
# Empieza en 4, termina antes de 1 (no llega), y va de -0.25 en -0.25
secuencia = np.arange(4, 1, -0.25)
print(secuencia)

[4.   3.75 3.5  3.25 3.   2.75 2.5  2.25 2.   1.75 1.5  1.25]


## Ejercicio 16
Lee la imagen "numpy.png" usando Pillow, y guárdala en un array.

In [16]:
# Pillow (PIL) es una librería para trabajar con imágenes
from PIL import Image

# Abrimos la imagen con Image.open()
imagen = Image.open("img/numpy.png")

# np.array() convierte la imagen en un array de números
# Cada píxel se convierte en valores RGB (rojo, verde, azul)
array_imagen = np.array(imagen)

# Vemos la forma: (alto, ancho, canales_de_color)
print("Forma del array:", array_imagen.shape)
print("Tipo de dato:", array_imagen.dtype)

FileNotFoundError: [Errno 2] No such file or directory: 'img/numpy.png'

## Ejercicio 17
Crea un array de 4x1. A continuación convierte el array a un 2x2

In [17]:
# Creamos un array de 4 filas y 1 columna
array_4x1 = np.array([[1], [2], [3], [4]])
print("Array 4x1:")
print(array_4x1)
print("Forma:", array_4x1.shape)

# Lo convertimos a 2x2 con reshape
# 4 elementos total: 2 filas x 2 columnas = 4, cuadra
array_2x2 = array_4x1.reshape(2, 2)
print("\nArray 2x2:")
print(array_2x2)
print("Forma:", array_2x2.shape)

Array 4x1:
[[1]
 [2]
 [3]
 [4]]
Forma: (4, 1)

Array 2x2:
[[1 2]
 [3 4]]
Forma: (2, 2)


## Ejercicio 18
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [18]:
# np.random.random() genera números aleatorios entre 0 y 1
# Le pasamos la forma que queremos: (4, 5, 3)
# Esto significa: 4 matrices, cada una de 5 filas y 3 columnas
# Son 3 dimensiones: la primera es "cuántas matrices", la segunda filas, la tercera columnas
array_3d = np.random.random((4, 5, 3))

print("Forma:", array_3d.shape)
print("Dimensiones:", array_3d.ndim)
print(array_3d)

Forma: (4, 5, 3)
Dimensiones: 3
[[[0.58257235 0.68648855 0.26287032]
  [0.45017195 0.27941276 0.73647684]
  [0.97674948 0.10746891 0.38720227]
  [0.31365801 0.49120946 0.45623613]
  [0.91675035 0.04983163 0.55924154]]

 [[0.5224375  0.71792861 0.34865071]
  [0.1971065  0.2593952  0.34078716]
  [0.24479763 0.09292546 0.71394756]
  [0.35715224 0.26065839 0.14832548]
  [0.27182924 0.03895524 0.61795115]]

 [[0.47548131 0.98272095 0.93376608]
  [0.91025238 0.06132829 0.50088829]
  [0.34091116 0.53758215 0.21120217]
  [0.96124743 0.42360303 0.74335484]
  [0.42169326 0.86759391 0.78260974]]

 [[0.89555377 0.91037541 0.90161756]
  [0.82693044 0.80173761 0.39037072]
  [0.56020339 0.65352132 0.84248198]
  [0.61403725 0.43495302 0.24753241]
  [0.56878269 0.5658611  0.25176084]]]


## Ejercicio 19
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

In [19]:
# np.zeros() crea un array de ceros
# dtype=bool convierte 0 en False
array_false = np.zeros((10, 1), dtype=bool)
print("Array 10x1:")
print(array_false)

# Lo transformamos a 2x5
array_2x5 = array_false.reshape(2, 5)
print("\nArray 2x5:")
print(array_2x5)

Array 10x1:
[[False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]]

Array 2x5:
[[False False False False False]
 [False False False False False]]


## Ejercicio 20
Dado el siguiente array

```Python
x = np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuánta es la longitud cada dimensión?

In [20]:
x = np.random.randint(10, 20, size=(5, 2, 6))

# 1. Cuántos elementos tiene: .size nos da el total
# 5 * 2 * 6 = 60 elementos
print("Elementos totales:", x.size)

# 2. Cuántas dimensiones: .ndim nos dice cuántas dimensiones tiene
print("Dimensiones:", x.ndim)

# 3. Longitud de cada dimensión: .shape nos da una tupla con el tamaño de cada dimensión
print("Forma (shape):", x.shape)
# (5, 2, 6) → 5 matrices de 2 filas y 6 columnas

Elementos totales: 60
Dimensiones: 3
Forma (shape): (5, 2, 6)
