![imagen](./img/ejercicios.png)

In [5]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden, usando numpy.

In [6]:
# 1. Creamos el array del 0 al 9
my_array = np.arange(10)
print("Array original:", my_array)

# 2. Imprimimos [9 7 5 3 1] → es el array al revés, pero solo los impares
# [::-2] significa: recorre el array de atrás a adelante, de 2 en 2
print("Resultado:", my_array[::-2])

Array original: [0 1 2 3 4 5 6 7 8 9]
Resultado: [9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [7]:
# Queremos [8 7] → empezamos en la posición 8, vamos hacia atrás hasta la 6 (sin incluir)
# [8:6:-1] → desde posición 8, hasta posición 6 (sin incluir), yendo hacia atrás
print(my_array[8:6:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [8]:
# Queremos [2 1 0] → desde la posición 2 hasta el inicio, yendo hacia atrás
# [2::-1] → desde posición 2, hasta el principio, de 1 en 1 hacia atrás
print(my_array[2::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [9]:
# 1. Creamos la secuencia del 1 al 20 y la ponemos en forma 4x5
matriz = np.arange(1, 21).reshape(4, 5)
print("Matriz original:")
print(matriz)

# 2. Invertimos filas Y columnas
# [::-1] invierte las filas (de abajo a arriba)
# [:, ::-1] invierte las columnas (de derecha a izquierda)
# Juntos: [::-1, ::-1] invierte todo
invertida = matriz[::-1, ::-1]
print("\nMatriz invertida:")
print(invertida)

Matriz original:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Matriz invertida:
[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [10]:
# Queremos las 2 primeras filas y las 2 primeras columnas
# [:2] → filas 0 y 1 (las 2 primeras)
# [:2] → columnas 0 y 1 (las 2 primeras)
print(matriz[:2, :2])

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [11]:
# Queremos filas 0 y 2 (saltando una) y columnas 0, 2, 4 (saltando una)
# [::2] → de 2 en 2 en filas → filas 0 y 2
# [::2] → de 2 en 2 en columnas → columnas 0, 2 y 4
print(matriz[::2, ::2])

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [12]:
# Queremos las 3 primeras filas con las columnas al revés
# [:3] → las 3 primeras filas
# [::-1] → las columnas invertidas
print(matriz[:3, ::-1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [13]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

# Manera 1: con máscara booleana
# x == "Loro" crea [True, False, False, True, False]
# Usamos esa máscara para filtrar
loros_1 = x[x == "Loro"]
print("Con máscara:", loros_1)

# Manera 2: con np.where()
# np.where() nos da las POSICIONES donde se cumple la condición
posiciones = np.where(x == "Loro")
loros_2 = x[posiciones]
print("Con where:", loros_2)

Con máscara: ['Loro' 'Loro']
Con where: ['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [14]:
# Creamos una secuencia del 0 al 19 (20 elementos)
secuencia = np.arange(20)

# La transformamos en 2 matrices de 5x2
# 2 * 5 * 2 = 20 elementos, cuadra
array_3d = secuencia.reshape(2, 5, 2)
print("Forma:", array_3d.shape)
print(array_3d)

Forma: (2, 5, 2)
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [15]:
# Creamos un array de 10 ceros
array_ceros = np.zeros(10)

# .nbytes nos dice cuántos bytes ocupa en memoria
print("Ocupa en memoria:", array_ceros.nbytes, "bytes")

# Sustituimos el 4to elemento (posición 3, porque empezamos en 0)
array_ceros[3] = 1
print(array_ceros)

Ocupa en memoria: 80 bytes
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [16]:
# Creamos el vector del 10 al 49
vector = np.arange(10, 50)
print("Original:", vector)

# Lo invertimos con [::-1]
invertido = vector[::-1]
print("Invertido:", invertido)

Original: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
Invertido: [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [1, 2 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [17]:
def indices_no_cero(vector):
    """
    Recibimos un vector y devolvemos los valores que NO son cero.
    np.nonzero() nos da las posiciones donde los elementos no son 0.
    """
    # np.nonzero() devuelve las posiciones de los elementos que no son 0
    posiciones = np.nonzero(vector)
    # Usamos esas posiciones para sacar los valores
    return vector[posiciones]

# Probamos con el vector del enunciado
v = np.array([1, 2, 0, 0, 4, 0])
print(indices_no_cero(v))
# [1 2 4]

[1 2 4]


## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [18]:
# Creamos una matriz 10x10 con números aleatorios entre 0 y 1
matriz = np.random.random((10, 10))

# .min() nos da el valor más pequeño de toda la matriz
print("Valor mínimo:", matriz.min())

# .max() nos da el valor más grande
print("Valor máximo:", matriz.max())

Valor mínimo: 0.003815172434122105
Valor máximo: 0.9926396360042095


## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [19]:
# Creamos un vector de 30 números aleatorios
vector = np.random.random(30)

# .mean() calcula la media (la suma de todos dividido entre cuántos hay)
print("Media:", vector.mean())

Media: 0.5133905731963597


## Ejercicio 15
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [20]:
# Empezamos con un array de unos (todo 1s)
tamano = 5  # podemos cambiar el tamaño
array_borde = np.ones((tamano, tamano), dtype=int)

# Ahora ponemos 0s en el interior
# [1:-1, 1:-1] selecciona todo EXCEPTO la primera y última fila/columna
# Es decir, selecciona solo el interior
array_borde[1:-1, 1:-1] = 0

print(array_borde)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


## Ejercicio 16
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [21]:
# Creamos una matriz 8x8 de ceros
tablero = np.zeros((8, 8), dtype=int)

# Rellenamos con 1s en las posiciones "impares" como un tablero de ajedrez
# [::2] = filas pares (0, 2, 4, 6)
# [1::2] = columnas impares (1, 3, 5, 7)
tablero[::2, 1::2] = 1    # filas pares, columnas impares → ponemos 1
tablero[1::2, ::2] = 1    # filas impares, columnas pares → ponemos 1

print(tablero)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 17
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [22]:
# np.tile() repite un patrón como si fuera un azulejo (tile = azulejo)
# Nuestro patrón base es una mini-matriz 2x2:
patron = np.array([[0, 1],
                    [1, 0]])

# Lo repetimos 4 veces en filas y 4 en columnas → 8x8
tablero_tile = np.tile(patron, (4, 4))
print(tablero_tile)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [23]:
# Creamos la matriz 5x5 aleatoria
matriz = np.random.random((5, 5))

# Normalizar = (valor - media) / desviación estándar
# La media es el "centro" de los datos
# La desviación estándar mide cuánto se alejan los datos de la media
# Al normalizar, los datos quedan centrados en 0 con dispersión 1
media = np.mean(matriz)
desviacion = np.std(matriz)

normalizada = (matriz - media) / desviacion
print("Original:")
print(matriz)
print("\nNormalizada:")
print(normalizada)
print("\nMedia de la normalizada:", np.mean(normalizada))  # debería ser ~0
print("Desviación de la normalizada:", np.std(normalizada))  # debería ser ~1

Original:
[[0.20064857 0.27215713 0.70632743 0.36669378 0.28741625]
 [0.0997332  0.35356196 0.22187533 0.04819125 0.53846687]
 [0.58834171 0.21390082 0.20684868 0.50772744 0.0780554 ]
 [0.97950035 0.98434617 0.94743723 0.36419811 0.66012416]
 [0.4063789  0.72106525 0.18571975 0.15974315 0.33361835]]

Normalizada:
[[-0.78520118 -0.52601534  1.04765371 -0.18336316 -0.47070799]
 [-1.15097333 -0.23096001 -0.70826389 -1.33778933  0.43923587]
 [ 0.62000937 -0.73716783 -0.76272864  0.32781948 -1.22954545]
 [ 2.03778082  2.05534468  1.92156663 -0.19240881  0.88018799]
 [-0.0395227   1.10107159 -0.83931135 -0.93346464 -0.30324646]]

Media de la normalizada: -3.3306690738754695e-17
Desviación de la normalizada: 1.0


## Ejercicio 19
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [24]:
# 1. Secuencia del 0 al 10
array_19 = np.arange(11)
print("Original:", array_19)

# 2. Sustituimos por -1 los elementos entre 3 y 8
# Usamos np.where con DOS condiciones unidas por & (Y lógico)
# Necesitamos paréntesis alrededor de cada condición
array_menos1 = np.where((array_19 >= 3) & (array_19 <= 8), -1, array_19)
print("Con -1:", array_menos1)

# 3. Negamos los elementos entre 3 y 8 (les cambiamos el signo)
array_negado = np.where((array_19 >= 3) & (array_19 <= 8), -array_19, array_19)
print("Negados:", array_negado)

Original: [ 0  1  2  3  4  5  6  7  8  9 10]
Con -1: [ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]
Negados: [ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]
